language: generic
os: osx
osx_image: xcode6.4
before_install:
- brew update
- brew install python3
- brew upgrade node
- pip3 install --upgrade pip setuptools wheel
- openssl aes-256-cbc -K $encrypted_a95564d8ff0d_key -iv $encrypted_a95564d8ff0d_iv -in other/osx/sentry.py.enc -out kindlecomicconverter/sentry.py -d
install:
- pip3 install -r requirements.txt
- pip3 install certifi https://github.com/pyinstaller/pyinstaller/archive/develop.zip
- npm install -g appdmg
script: python3 setup.py build_binary
deploy:
  provider: releases
  api_key:
    secure: ZsluoJQ+diDTIjh5tvqdjAdWc1MJX6wSk5vTGFqLAMV0wK8ypGa2+qxDB0sTFR7SRhQlAfBFi0q//li+XdWn6rUkUTqjOuS9xwfdKIYXuIrIJolgsbSeenYuLeAM23VYdH6NYBHVSjIK6O1H7enRkzot4GKZk91A3MZ/SnqBjsc1KvUVmQF19xmLha1y0WYitDCy7P1cT8517Cbhg6q8yTBUn/YjfFKyuDdbQFWe894n767mr33yvm1asHtYUsPYSif6ZdvhNDtMxUMaJTX0lPG6pZQLYV2HQipppMYSdbmsQOhamjPVcF6Chy3TAK5433smk3SiNGjg2wyGiN74JYpcc0MnGE5a5ZaDzBaavSvFrGZiHeygzaZUtFx3spsqcTgdJ1LZZ1aDRTrDhzi3FMjUFDLuwyDD5nJyS9bRHE30T9me7VSAcdJGrz1joShSYK6VMFvHUG3wUk0Bd+3KJZ75lJnP6TqVLgLjkWN4rcaN9caWylzT3ximKuHDg2S2aB23YYC4HFOrYdABM9fGcnuCVDwr16bBNM8zOGxNPswKfLBX1YWBr6EOXbrypMnekZDK2T5aqTP8L0IbImGety7P8b54r7nRTqFnELYrkVxmM+fUKPMPXMm/mZadrGg3bHjZYXm+nq7V6oMI2gEcNbpzKxx6l9XOjiBjN0uk/A0=
  file_glob: true
  file: dist/KindleComicConverter_osx_*
  skip_cleanup: true
  on:
    repo: AcidWeb/kcc
    tags: true
